import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from '@/components/Header';
import { Navbar } from '@/components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
      </head>

      <body className={`...`}> {/* Mantenha sua className original aqui */}
        {/* Adicionamos a estrutura principal aqui */}
        <div className="bg-gray-900 text-white min-h-screen">
          <div className="container mx-auto">
            <Header />
            <Navbar />
            <main className="p-4 md:p-8">
              {children} {/* O conteúdo da página específica (ex: /ciclo) entra aqui */}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}